{{- if not .Values.mgmt.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kos-scaler.secretName" . }}
  labels:
    {{- include "kos-scaler.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.mgmt.secretKey }}: {{ required "mgmt.token must be set when mgmt.existingSecret is empty" .Values.mgmt.token | quote }}
{{- end }}
